spring.application.name=movie_mood

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.api.token=${TMDB_API_TOKEN}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1